apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-web-pvc
  labels:
    name: mediawiki-web-pvc
  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

