apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-db-pvc
  labels:
    name: mediawiki-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

