name: MediaWiki CI

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
  
      - name: Build Docker Image
        run: |
          docker build -t itsbharatsaini/mediawiki-app:${{ env.VERSION }} .
          docker login -u itsbharatsaini -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push itsbharatsaini/mediawiki-app:${{ env.VERSION }}
      
      # - name: Set up K8s
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      # - name: Deploy to Kubernetes through Helm
      #   run: |
      #     helm upgrade --install mediawiki-app ./mediawiki-chart --set image.tag=${{ env.VERSION }}